# Generated by Django 3.2.7 on 2021-09-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_code_managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_hours', models.PositiveIntegerField()),
            ],
        ),
    ]
