# Generated by Django 3.2.7 on 2021-09-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_machine_managment'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_managment',
            name='machine_rate',
            field=models.DecimalField(decimal_places=2, default=89.0, max_digits=10),
            preserve_default=False,
        ),
    ]
