# Generated by Django 3.2.7 on 2021-09-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_machine_managment_machine_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_managment',
            name='details',
            field=models.CharField(default='a machine', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Submit_Timecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=200)),
                ('contractor_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hours_worked', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours_used', models.PositiveIntegerField()),
                ('total_cost_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.job_code_managment')),
                ('machine_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.machine_managment')),
            ],
        ),
    ]
