# Generated by Django 3.2.7 on 2021-09-10 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_auto_20210910_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_code_managment',
            name='time_card',
            field=models.ManyToManyField(to='timesheet.Timecard'),
        ),
        migrations.AddField(
            model_name='machine_managment',
            name='time_card',
            field=models.ManyToManyField(to='timesheet.Timecard'),
        ),
        migrations.AddField(
            model_name='timecard',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submit_timecard',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
