# Generated by Django 3.2.7 on 2021-09-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_auto_20210910_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_code_managment',
            name='time_card',
        ),
        migrations.RemoveField(
            model_name='machine_managment',
            name='time_card',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='hours',
        ),
        migrations.CreateModel(
            name='Timecard_Machine_managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Machine_managment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.machine_managment')),
                ('time_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.timecard')),
            ],
        ),
        migrations.CreateModel(
            name='Timecard_Job_code_managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_code_managment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.job_code_managment')),
                ('time_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.timecard')),
            ],
        ),
    ]
