# Generated by Django 3.2.7 on 2021-09-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_auto_20210910_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_code_managment',
            name='time_card',
            field=models.ManyToManyField(through='timesheet.Timecard_Job_code_managment', to='timesheet.Timecard'),
        ),
        migrations.AddField(
            model_name='machine_managment',
            name='time_card',
            field=models.ManyToManyField(through='timesheet.Timecard_Machine_managment', to='timesheet.Timecard'),
        ),
    ]
